version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:6.4.2
    volumes:
      - .:/code/elasticsearch
    ports:
      - ${ELASTIC_PORT}:${ELASTIC_PORT}
    networks:
      - appsbridge
        
  postgres:
    image: postgres:12
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    networks:
      - appsbridge

  web:
    build:
      context: ./management/
      dockerfile: Dockerfile
    command: python ./management/manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - "8667:8000"
    volumes:
      - .:/code
      - ./static:/static
    depends_on:
      - elasticsearch
      - postgres
    networks:
      - appsbridge

networks:
  appsbridge:
    name: custom_network
